apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-streaming
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
        - name: nats-streaming
          image: nats-streaming:0.17.0
          args: [
            '-p',
            '4222',
            '-m',
            '8222',
            # 'hb' stands for Heartbeat
            '-hbi', # How often does the NATS Server will make a request to each of its client
            '5s',
            '-hbt', # How long each client should respond 
            '5s',
            '-hbf', # How long a client can fail before NATS server assume it's dead and gone
            '2',
            '-SD',
            '-cid',
            'ticketing'
          ]