apiVersion: v1
kind: Service
metadata:
  name: nats-streaming-service-clusterip
spec:
  selector:
    app: nats-streaming
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222