apiVersion: v1
kind: Service
metadata:
  name: auth-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000