apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: irfandyjip89/ticketing_auth
          env:
            - name: JWT_KEY # This is what you will look for in the container
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # This is the reference to the "Secret" object name
                  key: JWT_KEY