apiVersion: v1
kind: Service
metadata:
  name: orders-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000