apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: irfandyjip89/ticketing_orders
          env:
            - name: MONGO_URI
              value: mongodb://orders-mongo-service-clusterip:27017/orders
            - name: JWT_KEY # This is what you will look for in the container
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # This is the reference to the "Secret" object name
                  key: JWT_KEY
            - name: NATS_URL
              value: http://nats-streaming-service-clusterip:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom: # Get the pod's name
                fieldRef:
                  fieldPath: metadata.name