apiVersion: v1
kind: Service
metadata:
  name: tickets-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000