apiVersion: v1
kind: Service
metadata:
  name: payments-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000